### PR TITLE
Skip inserting CSS rules containing `@import` directives when piercing

### LINKED ISSUE #78: Error during piercing if CSS includes `@import` directives
Currently when we construct a copy of the existing stylesheets in order to prevent a FOUC during teleporting an existing `<fragment-host>` into a `<fragment-outlet>`, we see the following error if any of the stylesheets contain an `@import` directive.

```
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Can't insert @import rules into a constructed stylesheet.
```
https://github.com/web-fragments/web-fragments/blob/675ad7e8e49fa2bfb06eaca4c8b6bd1d3de2072f/packages/web-fragments/src/elements/fragment-host.ts#L113

We need to skip inserting these rules if they're encountered.

### PR DESCRIPTION
**Pull request by 1000hz**
This PR fixes #78, where a fragment containing CSS that includes `@import` directives would cause a runtime error during fragment piercing.

`@import` directives are currently not allowed inside of Constructed Stylesheets, so we need to skip over them when copying over style rules to the constructed stylesheet we use to avoid FOUC when reparenting the `<fragment-host>` into the `<fragment-outlet>`.

### CODE REVIEW

File: packages/web-fragments/src/elements/fragment-host.ts [hunk 1]
```diff
@@ -109,9 +109,12 @@ export class FragmentHost extends HTMLElement {
 
 					// CSSStyleSheet.insertRule() prepends CSS rules to the top of the stylesheet by default.
 					// We need to set the index to sheet.cssRules.length in order to append the rule and maintain specificity.
-					[...sheet.cssRules].forEach((rule) =>
-						clone.insertRule(rule.cssText, clone.cssRules.length)
-					);
+					[...sheet.cssRules].forEach((rule) => {
+						// @import directives are not allowed in Constructed Stylesheets
+						if (!(rule instanceof CSSImportRule)) {
```
Comment (IgorMinar) [inline packages/web-fragments/src/elements/fragment-host.ts:114]: I understand that this skips over the problematic imports, but wouldn't this mean that the teleported stylesheet is different then the original stylesheet as the imports will now be missing?

In other words, why is it safe to simply drop these imports?

Comment (IgorMinar) [reply packages/web-fragments/src/elements/fragment-host.ts:114]: This is a great context. thanks for explaining. Could you please add a shorter version as an inline comment where the import is dropped and maybe even link to this comment and atomic move spec? thanks!
